name: 'Bump version'

on:
  push:
    - 'master'

jobs:
    bump-version:
      name: Automatic Version Bump
      runs-on: ubuntu-latest
      uses: phips28/gh-action-bump-version@v9.0.1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path-wording: 'fix, fixes, patch'